{% set version = "2.2.0" %}
{% set sha256 = "09b16deb8547d3412ad7b590689584cd0fe25ec8db3be37788be3810cbf19cb1" %}
{% set pkg_name = "snowballstemmer" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: {{ pkg_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<36]
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  imports:
    - snowballstemmer
  requires:
    - python <3.10
    - pip
  commands:
    - pip check

about:
  home: https://github.com/snowballstem/snowball
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Snowball stemming library collection for Python'
  description: |
    Snowball is a small string processing language designed for creating
    stemming algorithms for use in Information Retrieval. The Snowball
    compiler translates a Snowball script into another language - currently
    ISO C, Java and Python are supported.
  dev_url: https://github.com/snowballstem/snowball
  doc_url: https://snowballstem.org/

extra:
  recipe-maintainers:
    - chohner
