{% set version = "3.0.1" %}
{% set name = "snowballstemmer" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d5eeeec8e9f84d4d56b847692bacf79bc2c8e90c7f80ca4444ff8b6f2e52895

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - src/sample/testapp.py
  imports:
    - snowballstemmer
  commands:
    - pip check
    - cd src/sample && python testapp.py "running quickly"
  requires:
    - pip

about:
  home: https://github.com/snowballstem/snowball
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Snowball stemming library collection for Python
  description: |
    Snowball is a small string processing language designed for creating
    stemming algorithms for use in Information Retrieval. The Snowball
    compiler translates a Snowball script into another language - currently
    ISO C, Java and Python are supported.
  dev_url: https://github.com/snowballstem/snowball
  doc_url: https://snowballstem.org

extra:
  recipe-maintainers:
    - chohner
