travis:
  secure:
    BINSTAR_TOKEN: X4QlKOy2qL+3j8mtH0xiS6eDW5KJ21qid88y7ewLoX5wN9lAS9gWdU/frGILEa9TxGb9nrB28qxrfIwayvH0l8Cvf8a9EfSEY7R0mwY7dsuAsXauGJ/suWAydKRCf/cyCg9+KCzctPaHRPECVOhR6aPNweLq7BIbj+WA+MQSr/bH31lgvOjFwzw7Wf9caMJvZmFmNQVYFtnJJFCtNJyGQ4dsMMmHaIl3qRVWOELjpVN2aXPfFjN0kUhuDnAVtd0XOgEsgFx+ZeLsri07eAOLYPPXpFdL9I6NQSyxLGY7LcEu2gZHO7hhDy31zAeYSub0iQ0EC9UKlQiBiquXjA3SPsaMfSL4LifdalDRhHkjgZjPmeAVj/ITz5biB3BFFOSkKpRRQuyBUvBccnrFS9Z2yLoFyzn3Ra7xd4sxTmtomCnm+DoEy3gXSXA6TYe4nGMIwS7u6rxhOECbJCRUhyjVTYOiagUQlaE18uf2OiNoit0I+pD2gzjSPduLuECqLv6UkRPxZphpaVvcDlwG7ScPeTcs5YnR7jsWKNdu+QZ9clTA84QNLxyGr2P4EKkt0r6XK7Db8rAnzfzIjJ/7TsFHYveA2NDM29QA6Wfjbs/+w8mhGPAd3jRytgViSUML3ln6RUFGFgiCs2/J7pP7K7bch/WM3unVdmC4XR9RKF50ATw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
