travis:
  secure:
    BINSTAR_TOKEN: P7OYtrg14t5pXfwjGYr2ybdNcJBdDXQ2mFzeRNOQkZy8/U3XQJdPk8IeO0bXt2eLQEER2CESB1DEP3IlFx4oQcc3S6zee8hAEs3JAw/k7q1yiF2CAgBQwL3e5CRXGeS58cG1rcF0d7LJ8Yfs8hn8wPh5TFsSslBnfrSvfDQYcH0+eBNRuohlUfNgqRaPxvY9faqiIvh0ugO+wJu3FyRk3ubgRn6Km0iaeTHcz2KSVQEHm+5YPLET4rWIpH+qzbpR/5CPxkA8uu3E5To+rmCKqKjKBh1FUfaX6lia3FJJv21qBIDjXT/mMgRn72PXAQuxH2TBf00H78eWbvTMEbArWSWANwweLo/5RBkMwgHpBWJXjBLdG5yOYaYznqSFn2H39NmSdNR1q2kvV1hbfYMJZk7AW/1yqtZwTps0muyfaMMSsFQuGBRWlojuuPol6CIXsvFbL0+R8vmqXyTyZD409U98wnj9xiye0RB7NwBB7lhnurUG+DgxeWHTH/XbYa3tk+OyfSRG54UdYzcS62vII6JxS7M4ufcUR5bvlMR+qz2Z5TuasjTRrxV7mvXqIXS1q2lDP3QfboXnFJIhd98ML+2+3+EeJjMIOPwaVAX6IWKrGf9sb2inIY2QTCMetgivWjsHd17NfkxqEYfqGwgrWvW4Uvk5QuyCKaZAQCw9Ypg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
