travis:
  secure:
    BINSTAR_TOKEN: D9BoIyi461wFy+U2VDdBZakl64Cw3f7u8xw0I3+loBeXpxkXYP7zryi8LEKzSgOrRx/s0dP/p+B7f/wsq5h3UNYivaBJFNYFFDianaJE8LM58sqbCTwnT6+C60V/0LekWLrTrIQOnGzP2VBwivvqFtFD82NkY4Mg5iOZhFNTnTj8xxWxhX+5+cNxQT+X7nFgBSSlB2T10Da8o/ckGPuFxAKx09zWgsrBCxwzfFi2DnQCLTqz57zDokgC6SqRpTJ/v02ZWbwXM5A6fjeonLzGrD5ChL705LAoRxWtugeLpXBztpKSpWljg+YaMve56R+CXn12/zo6G13AEFXic4uxyL+9N4HQ9pPdw/lZlqc6dzCYC3D7IaCQ6M0KrgzKZtB/h1O9Wl52enebfes7HEpzLYCk7P3yIhE8Ryz95B5g7iaFZrX1r7lBnKXsx6I1IZKjBaROQZamy1EdDVrpSbkQ/LYpncEzBFAJTTUP3ra79BOuwevI5NY+XIyxI2RB6k5BBM78hv/6URSDQ2hCj47+phTmJuXfBFDXN/kvf1H/a2yrucIUTjUTswwxseI1lJsZoj2cNGtdfxXkL5Q9AqACYbdd99TezERZMUFVhNJwnCdpaThc72XPi3OXeDGhQumIxcNMI6pSrKLOXxHhgm+iP6vTLZ6BKhbZK6YAUYK12Wc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
